# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20160924_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, verbose_name='契約状況')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
            ],
        ),
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.AgreementStatus'),
        ),
    ]
