# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20160924_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField(verbose_name='郵便番号')),
                ('add', models.CharField(max_length=50, verbose_name='住所')),
                ('station', models.CharField(max_length=10, verbose_name='駅')),
                ('working', models.IntegerField(verbose_name='徒歩')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='都道府県')),
            ],
        ),
        migrations.CreateModel(
            name='Duties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='役割')),
                ('content', models.CharField(max_length=200, verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='SubProjectOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='プロジェクト名')),
                ('comment', models.CharField(max_length=200, verbose_name='comment')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Project')),
            ],
        ),
        migrations.CreateModel(
            name='UnitPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('price', models.IntegerField(verbose_name='単価')),
            ],
        ),
        migrations.CreateModel(
            name='WorkScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='作業範囲')),
                ('initial', models.CharField(max_length=10, verbose_name='略称')),
                ('content', models.CharField(max_length=100, verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='WorkScopeBottom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkScope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.WorkScope')),
            ],
        ),
        migrations.CreateModel(
            name='WorkScopeTop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workscope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.WorkScope')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectoverview',
            name='project',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='agreement',
            name='work_add',
            field=models.IntegerField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.DeleteModel(
            name='ProjectOverview',
        ),
        migrations.AddField(
            model_name='subprojectoverview',
            name='work_scope_bottom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.WorkScopeBottom'),
        ),
        migrations.AddField(
            model_name='subprojectoverview',
            name='work_scope_top',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.WorkScopeTop'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.City'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='duties',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Duties'),
        ),
        migrations.AddField(
            model_name='user',
            name='unit_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.UnitPrice'),
        ),
    ]
