# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20161001_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workscopebottom',
            old_name='WorkScope',
            new_name='workScope',
        ),
        migrations.AlterField(
            model_name='workscope',
            name='name',
            field=models.CharField(max_length=100, verbose_name='作業範囲'),
        ),
    ]
