# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20161001_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='work_add',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Address'),
        ),
    ]
