# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20161002_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workscopebottom',
            old_name='workScope',
            new_name='workscope',
        ),
    ]
