# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20161002_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='unitprice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.User'),
        ),
    ]
