# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20161002_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='資格名')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='railway_routes',
            field=models.CharField(default='', max_length=50, verbose_name='路線'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='appeal',
            field=models.CharField(default='', max_length=1000, verbose_name='アピール'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='final_education',
            field=models.CharField(default='', max_length=200, verbose_name='最終学歴'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_kana',
            field=models.CharField(default='', max_length=30, verbose_name='メイ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_kana',
            field=models.CharField(default='', max_length=30, verbose_name='セイ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(default='', max_length=100, verbose_name='国籍'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.License'),
        ),
    ]
