# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20161008_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenselevel',
            name='comment',
            field=models.CharField(default='', max_length=300, verbose_name='内容'),
            preserve_default=False,
        ),
    ]
