# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_licenselevel_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='name',
            new_name='license',
        ),
    ]
