# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20161008_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='status',
            new_name='agreement_status',
        ),
        migrations.RenameField(
            model_name='license',
            old_name='level',
            new_name='license_level',
        ),
        migrations.RenameField(
            model_name='subprojectenvironmentskill',
            old_name='subproject',
            new_name='subproject_overview',
        ),
        migrations.RenameField(
            model_name='subprojectenvironmentskill',
            old_name='environment',
            new_name='user_develop_environment_skill',
        ),
        migrations.RenameField(
            model_name='subprojectprogrammingskill',
            old_name='subproject',
            new_name='subproject_overview',
        ),
        migrations.RenameField(
            model_name='subprojectprogrammingskill',
            old_name='program',
            new_name='user_program_skill',
        ),
        migrations.RenameField(
            model_name='userdevelopenvironmentskill',
            old_name='environment',
            new_name='develop_environment',
        ),
        migrations.RenameField(
            model_name='userprogrammingskill',
            old_name='program',
            new_name='programming_language',
        ),
    ]
