# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-22 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20161010_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='position',
        ),
        migrations.AddField(
            model_name='subprojectoverview',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='終了日'),
        ),
        migrations.AddField(
            model_name='subprojectoverview',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='開始日'),
        ),
    ]
