# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-22 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20161023_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='subprojectoverview',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Position'),
        ),
    ]
