# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-13 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_auto_20170810_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprojectoverview',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Agreement'),
        ),
    ]
