# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_user_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth',
        ),
    ]
