# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 01:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0025_remove_user_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
